name: Yarn install
description: Install and cache node modules with yarn
inputs:
  npm_token:
    description: 'NPM access token'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
    value: ${{ steps.node-modules-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Set node version
      id: set-node-version
      shell: bash
      run: echo "::set-output name=version::$(node -v)"

    - name: Cache node_modules folder
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles('**/yarn.lock') }}

    - name: yarn install
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
      run: |
        yarn install --frozen-lockfile --ignore-optional --non-interactive
