name: Yarn install
description: Install and cache node modules with yarn
inputs:
  node-version:
    description: 'Specify node version'
    required: false
    default: '14.17'
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Checkout project
      uses: actions/checkout@v2

    - name: Set node version
      id: set-node-version
      shell: bash
      run: echo "::set-output name=version::$(node -v)"

    - run: ls -l
      shell: bash

    - name: Cache node_modules folder
      uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}--node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles('**/yarn.lock') }}

    - run: ls -l
      shell: bash

    - name: yarn install
      shell: bash
      run: yarn install

    - run: ls -l
      shell: bash