name: Cache with oneliner

on: push

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v2
        id: yarn-cache
#        with:
#          directory: 'path/to/package'

      - name: Cache does not exist
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo "Cache does not exist!"

      - name: yarn install
        run: yarn install