name: Integration Tests Matrix
description: Creates matrix for integration tests. Considers monorepo

inputs:
  parallel_groups:
    description: How many parallel instances to run per each package
    required: false
    default: 2
  parallel_matrix:
    description: Custom matrix as an array of objects with pkg, location and parallel_groups keys
    required: false

outputs:
  matrix:
    description: Matrix for strategy
  isMonorepo:
    description: Whether the project is a monorepo

runs:
  using: node16
  main: dist/index.js
