name: Report Coverage
description: Downloads coverage file(s) and print a report as a PR comment

inputs:
  name:
    description: Name of uploaded coverage
    required: false
    default: code-coverage
  reporter:
    description: Specify istanbul reporter for PR comment # https://istanbul.js.org/docs/advanced/alternative-reporters/
    required: false
    default: text-summary
  token:
    description: GitHub token
    required: false

runs:
  using: composite
  steps:
    - name: Download Coverage
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: code-coverage

    - name: Merge coverage files
      shell: bash
      run: |
        mkdir merged-coverage
        npx nyc merge code-coverage merged-coverage/coverage.json

    - name: Print Coverage
      uses: tj-actions/coverage-reporter@3eef0fe5e5d3881cc8faa2fb1365296edbf8af60
      with:
        coverage-command: npx nyc report --reporter ${{ inputs.reporter }} --temp-dir merged-coverage
        token: ${{ inputs.token || github.token }}

