name: Hello
author: Ondrej Tuma
description: Print out hello
inputs:
  who-to-gree:
    description: 'Who to greet'
    required: true
    default: man
outputs:
  time:
    description: 'Greeting time'
runs:
  using: "node16"
  main: "index.js"