name: Create Matrix
description: >
  Creates parallelization matrix. 
  By default creates 2 instances for SPA or 2 instances for each package in monorepo.

inputs:
  parallel_groups:
    description: How many parallel instances to run per each package
    required: false
    default: 2
  parallel_matrix:
    description: Custom matrix as an array of objects with pkg, location and parallel_groups keys
    required: false
  npm_token:
    description: NPM token if your project use private packages
    required: false

outputs:
  matrix:
    description: |
      Matrix for strategy. Returns:
      [
        { pkg: string, location: string, index: number, total?: number }, // defined instance
        ...
      ]
  isMonorepo:
    description: Whether the project is a monorepo. Returns boolean

runs:
  using: node16
  main: dist/index.js
