name: Integration Tests
description: Run integration tests and upload screenshots on failure

inputs:
  screenshots:
    description: 'Artifact name for screenshot'
    required: false
    default: cypress-screenshots
  command:
    description: Command to be run as integration test
    required: false
    default: yarn test:integration:ci

runs:
  using: composite
  steps:
    - name: Cache Cypress folder
      uses: actions/cache@v2
      with:
        path: '~/.cache/Cypress'
        key: cypress-${{ hashFiles('**/yarn.lock') }}

    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        install: false
        command: ${{ inputs.command }}

    - name: Store Cypress Screenshots Artifact
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ inputs.screenshots }}
        path: |
          **/cypress/screenshots
        retention-days: 3
