name: Test action

on: push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-install
        id: yarn-install
      - name: Cache exists
        if: steps.yarn-install.cache-hit == 'true'
        run: 'Cache is here!'
      - run: du -hs node_modules
