name: Cache with native action

on: push

jobs:
  save-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set cache dir
        id: set-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Set node version
        id: set-node-version
        run: echo "::set-output name=version::$(node -v)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.set-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules folder
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ steps.set-node-version.outputs.version }}-yarn-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache does not exist
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: echo "Cache does not exist!"

      - name: yarn install
        run: yarn install