name: CD

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types:
      - completed

jobs:
  sucess:
    name: Log success
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"