name: Test concurrency

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print_success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"
      - run: echo "Done!"