name: Insert SVG

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master, main]

jobs:
  insert:
    name: Insert SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Generate the affected packages report
        uses: toptal/davinci-github-actions/report-affected-packages
