name: Insert SVG

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master, main]

jobs:
  insert:
    name: Insert SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Put it in
        run: echo "![foo svg](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_HEAD_REF/foo.svg)" >> $GITHUB_STEP_SUMMARY
        shell: bash
