name: Trigger Integration Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  WORKFLOW_NAME: integration-tests.yml

jobs:
  trigger_workflow:
    name: Triggering
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Integration Tests
        uses: actions/github-script@v4
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.issue;
            const workflow_id = '${{ env.WORKFLOW_NAME }}';
            const ref = '${{ github.head_ref }}';
            
            github.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref,
            })
